server:
  port: 8080
  contextPath: /Restaurant
---
spring:
  profiles: local
datasource:
  ccapp:
    url: jdbc:h2:~/hms
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod,default
datasource:
  ccapp:
    url: jdbc:mysql://localhost:3306/hms
    username: admin
    password: password
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect